# Generated by Django 4.1.3 on 2022-12-15 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_fullname_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 15, 11, 56, 47, 921623, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
