# Generated by Django 4.1.3 on 2022-12-17 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_date_of_birth_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 17, 12, 10, 38, 884610, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
