# Generated by Django 4.1.3 on 2023-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
