# Generated by Django 4.1.3 on 2023-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
