# Generated by Django 4.1.3 on 2023-02-17 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 12, 38, 25, 426394, tzinfo=datetime.timezone.utc)),
        ),
    ]
