# Generated by Django 4.1.3 on 2023-02-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfigurations',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configurations', to='product.productitem'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='product.product'),
        ),
        migrations.AlterField(
            model_name='promotioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='product.category'),
        ),
        migrations.AlterField(
            model_name='promotioncategory',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='product.promotion'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_variations', to='product.category'),
        ),
    ]
