# Generated by Django 4.1.3 on 2022-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_productsizes_productsimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
