# Generated by Django 4.1.3 on 2022-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statement',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
