# Generated by Django 4.1.3 on 2022-12-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_reviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='content',
            new_name='comment',
        ),
    ]
