# Generated by Django 4.1.3 on 2023-01-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_options_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
