# Generated by Django 4.1.3 on 2022-12-07 14:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='statement',
            field=tinymce.models.HTMLField(),
        ),
    ]
