# Generated by Django 4.1.3 on 2022-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='statement',
            field=models.TextField(),
        ),
    ]
