# Generated by Django 4.1.3 on 2022-12-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='updated',
        ),
    ]
